### ISSUE TITLE
Transaction from yesterday appearing as received “Just now” Blockchain syncing to 2000??

### ISSUE THREAD

**Issue by Datsun240** [Racecraft/digibytewallet-ios#109]
**What happened:**
```
Transaction from yesterday appearing as received “Just now” Blockchain syncing to 2000??
```

**Version:** 2.0.0 (1241)

**Operating system:** iOS 11.2.2

**Model:** iPhone 7

**Memory:** 98% (1.18 GB used out of 1.21 GB)

**Capacity:** 82% (24.4 GB used out of 29.8 GB)

**Locale:** United States English

**Network:** AT&T LTE (4G)

**WiFi:** Connected

**Attachments:** 

![IMG_3774.PNG](http://buglife.s3.amazonaws.com/report_attachments/aebd3ceaddc72ac373f958d104b63c576a44c0fc/original/IMG_3774.PNG?1518329125)

**URL:** http://buglife.com/apps/breadwallet/reports/78

Reported via Buglife

**Comment by gto90** [comment]
This issue has been resolved in the latest build
