### ISSUE TITLE
Sent 17 to iOS beta wallet from shapeshift. Hasn’t arrived yet when all other transactions were almost instant. Hope this helps. 

### ISSUE THREAD

**Issue by Datsun240** [Racecraft/digibytewallet-ios#111]
**What happened:**
```
Sent 17 to iOS beta wallet from shapeshift. Hasn’t arrived yet when all other transactions were almost instant. Hope this helps. 
```

**Version:** 2.0.0 (1258)

**Operating system:** iOS 11.2.5

**Model:** iPhone 6S

**Memory:** 99% (1.56 GB used out of 1.58 GB)

**Capacity:** 51% (15.2 GB used out of 29.8 GB)

**Locale:** United States English

**Network:** T-Mobile LTE (4G)

**WiFi:** Connected

**Attachments:** 

![IMG_2223.PNG](http://buglife.s3.amazonaws.com/report_attachments/ff90ac4d5b40ecc7ee5968e6678311b78aceafe1/original/IMG_2223.PNG?1518416246)

![IMG_2224.PNG](http://buglife.s3.amazonaws.com/report_attachments/3edaa2a9842557790c44286b7829b7bf12c3035f/original/IMG_2224.PNG?1518416251)

**URL:** http://buglife.com/apps/breadwallet/reports/80

Reported via Buglife

**Comment by gto90** [comment]
This issue is resolved in the latest build.

**Comment by gto90** [comment]
This issue is resolved in the latest build
