### ISSUE TITLE
Is this correct ? 

### ISSUE THREAD

**Issue by Datsun240** [Racecraft/digibytewallet-ios#114]
**What happened:**
```
Is this correct ? 
```

**Version:** 2.0.0 (1258)

**Operating system:** iOS 11.2.5

**Model:** iPhone 8

**Memory:** 98% (1.25 GB used out of 1.28 GB)

**Capacity:** 40% (23.8 GB used out of 59.6 GB)

**Locale:** United Kingdom English

**Network:** EE HSDPA (3.5G)

**WiFi:** Connected

**Attachments:** 

![asset.PNG](http://buglife.s3.amazonaws.com/report_attachments/565f3c1a59ac19bfb250d8e77bd99bdd118f81d8/original/asset.PNG?1518627798)

**URL:** http://buglife.com/apps/breadwallet/reports/83

Reported via Buglife

**Comment by gto90** [comment]
This issue has been resolved on the latest build.
