### ISSUE TITLE
Cant send any dgb

### ISSUE THREAD

**Issue by Datsun240** [Racecraft/digibytewallet-ios#116]
**What happened:**
```
Cant send any dgb
```

**Version:** 2.0.0 (1258)

**Operating system:** iOS 10.3.3

**Model:** iPhone 7 Plus

**Memory:** 98% (1.73 GB used out of 1.77 GB)

**Capacity:** 57% (67.9 GB used out of 119 GB)

**Battery:** 11%(Charging)(Low power mode)

**Locale:** Netherlands Dutch; Flemish

**Network:** vf nl LTE (4G)

**WiFi:** Disconnected

**Attachments:** 

![IMG_3041.PNG](http://buglife.s3.amazonaws.com/report_attachments/e134dd341332bbc1f07c0da5db80ee8cd42d6028/original/IMG_3041.PNG?1518719131)

**URL:** http://buglife.com/apps/breadwallet/reports/85

Reported via Buglife

**Comment by gto90** [comment]
This issue is resolved in the latest build.
