### ISSUE TITLE
Hi, I imported my wallet with a passphrase, the wallet has successfully synchronized, but the balance in the wallet iz zero, instead of 18122 DGB, as I have rechecked in rhe dgb explorer. My last transaction was of January 2017, so may be the wallet did not synchronized that far... Can I fix the balance information in the app? Thank you!! Andrej

### ISSUE THREAD

**Issue by Datsun240** [Racecraft/digibytewallet-ios#118]
**What happened:**
```
Hi, I imported my wallet with a passphrase, the wallet has successfully synchronized, but the balance in the wallet iz zero, instead of 18122 DGB, as I have rechecked in rhe dgb explorer. My last transaction was of January 2017, so may be the wallet did not synchronized that far... Can I fix the balance information in the app? Thank you!! Andrej
```

**Version:** 2.0.0 (1268)

**Operating system:** iOS 11.2.5

**Model:** iPhone 6

**Memory:** 91% (659 MB used out of 725 MB)

**Capacity:** 55% (65.6 GB used out of 119 GB)

**Locale:** Czech Republic English

**Network:** VF CZ LTE (4G)

**WiFi:** Connected

**Attachments:** 

**URL:** http://buglife.com/apps/breadwallet/reports/87

Reported via Buglife

**Comment by gto90** [comment]
This sounds like you have restored the incorrect passphrase.  Please also try restoring your passphrase to the new Android wallet or check your passphrase to ensure you have used the correct one.  Additionally, you should refrain from sending/receiving large quantities of DGB with the iOS or Android wallets until they are no longer in beta.
