### ISSUE TITLE
Did not sign tx within timeout

### ISSUE THREAD

**Issue by DeefK** [Racecraft/digibytewallet-ios#12]
Trying to send 4,999819 dgb to a litebit adress (total of 5 with fee). 
When entering password i get the error Did not sign tx within timeout

**Comment by gto90** [comment]
@DeefK ,

Can you try enabling a manual node and attempt to reproduce the issue again?  Thanks.

**Comment by gto90** [comment]
This issue will be resolved once we have a solid dns seed in place.
