### ISSUE TITLE
Sync stuck at 20th feb. Force to close then restart is not save me.

### ISSUE THREAD

**Issue by Datsun240** [Racecraft/digibytewallet-ios#121]
**What happened:**
```
Sync stuck at 20th feb. Force to close then restart is not save me.
```

**Version:** 2.0.0 (1274)

**Operating system:** iOS 11.2.6

**Model:** iPhone 7

**Memory:** 94% (1.32 GB used out of 1.41 GB)

**Capacity:** 85% (25.3 GB used out of 29.8 GB)

**Locale:** Turkey Turkish

**Network:** Turk Telekom LTE (4G)

**WiFi:** Connected

**Attachments:** 

**URL:** http://buglife.com/apps/breadwallet/reports/90

Reported via Buglife

**Comment by PeterStaev** [comment]
Same here. Stuck on `20 Feb 2018, 22:15`. Forceclosing doesn't have any effect. But also reinstalling and performing a full resync has no effect. Even tried using a local node that is fully synced, but still stuck on this date/time.

**Comment by PeterStaev** [comment]
Btw, seems this is some specific block and #122 is the same as this issue. My timezone is GMT+2, in the other issue the user complains that it is stuck on `21 Feb 2018, 04:15`. Assuming he is in the Philippine timezone (since he is using that locale) which is GMT+8, so exactly 6 hours difference.

**Comment by emnavalta** [comment]
Yeah I’m from the Philippines. It gets stuck on Feb 21, 2018 4:15am. It’s been three days since this happened. Some 40k DGB are stuck on my mobile wallet as a result.
