### ISSUE TITLE
Ik stuurde gisteravond dgb van litebit.eu naar mijn iOS wallet. Alleen het is niet aangekomen.
Vorige keer lukte het wel gewoon alleen nu niet.

Hoe kan dit opgelost worden?

### ISSUE THREAD

**Issue by Datsun240** [Racecraft/digibytewallet-ios#126]
**What happened:**
```
Ik stuurde gisteravond dgb van litebit.eu naar mijn iOS wallet. Alleen het is niet aangekomen.
Vorige keer lukte het wel gewoon alleen nu niet.

Hoe kan dit opgelost worden?
```

**Version:** 2.0.0 (1274)

**Operating system:** iOS 11.2.5

**Model:** iPhone 8

**Memory:** 95% (1.25 GB used out of 1.32 GB)

**Capacity:** 44% (26.3 GB used out of 59.6 GB)

**Locale:** Netherlands Dutch; Flemish

**Network:** vf nl LTE (4G)

**WiFi:** Connected

**Attachments:** 

![asset.HEIC.jpg](http://buglife.s3.amazonaws.com/report_attachments/f43a610325540124a3b9b4c83230965ba998b274/original/asset.HEIC.jpg?1519648141)

![asset.HEIC.jpg](http://buglife.s3.amazonaws.com/report_attachments/339b12f166ab515cadf4a48551afcd00335e2e6f/original/asset.HEIC.jpg?1519648144)

**URL:** http://buglife.com/apps/breadwallet/reports/95

Reported via Buglife

**Comment by istapelk** [comment]
Het is gewoon aangekomen op adres DU47AvJnT8AMgQyAz5BSeHU8iyCj4GHYHg zie ik.
Kan je verifiëren dat dit adres ook het adres in je Digibyte Wallet App is?

**Comment by gto90** [comment]
This issue is resolved in the latest build.
