### ISSUE TITLE
Sync is stuck in (DigiWallet 2.0)

This is on iPhone 10 iOS 11.2.5, fast network.

### ISSUE THREAD

**Issue by Datsun240** [Racecraft/digibytewallet-ios#127]
**What happened:**
```
Sync is stuck in (DigiWallet 2.0)

This is on iPhone 10 iOS 11.2.5, fast network.
```

**Version:** 2.0.0 (1274)

**Operating system:** iOS 11.2.5

**Model:** iPhone X

**Memory:** 99% (2.13 GB used out of 2.15 GB)

**Capacity:** 31% (18.4 GB used out of 59.5 GB)

**Locale:** United States English

**Network:** AT&T

**WiFi:** Connected

**Attachments:** 

![IMG_0082.PNG](http://buglife.s3.amazonaws.com/report_attachments/98125c8cedf574beabf907bd9accc39c92a81510/original/IMG_0082.PNG?1519651764)

**URL:** http://buglife.com/apps/breadwallet/reports/96

Reported via Buglife

**Comment by SmartArray** [comment]
Issue fixed.

https://github.com/Racecraft/digibytewallet-ios/pull/129/commits/c03518db418c747d98ab98ed8ec12b3f82f6b9c6
