### ISSUE TITLE
I am sending small amounts of DGB from H2C and the blocks factory pools, since transaction is showed as done, I am unable to see them reflected in balance, current balance doesn’t changes

### ISSUE THREAD

**Issue by Datsun240** [Racecraft/digibytewallet-ios#128]
**What happened:**
```
I am sending small amounts of DGB from H2C and the blocks factory pools, since transaction is showed as done, I am unable to see them reflected in balance, current balance doesn’t changes
```

**Version:** 2.0.0 (1274)

**Operating system:** iOS 11.2.5

**Model:** iPhone 7 Plus

**Memory:** 92% (2.57 GB used out of 2.78 GB)

**Capacity:** 24% (58.3 GB used out of 238 GB)

**Locale:** Colombia Spanish; Castilian

**Network:** movistar LTE (4G)

**WiFi:** Connected

**Attachments:** 

**URL:** http://buglife.com/apps/breadwallet/reports/97

Reported via Buglife

**Comment by gto90** [comment]
This should be resolved in the latest build.
