### ISSUE TITLE
Does not restore correctly a DGB Go wallet

### ISSUE THREAD

**Issue by PeterStaev** [Racecraft/digibytewallet-ios#13]
I've tried restoring a DGB Go wallet using the backup phrase provided by the Go wallet. And although all transaction have been made in 2018, nothing is restored in the app. Also tried resyncing blockchain but still nothing happens.

**Comment by gto90** [comment]
@PeterStaev ,

I will have to confirm with the Go Wallet team, but do you know if the Go Wallet is a BIP39 Compatible Wallet?  That is, does your Go Wallet seed phrase contain 12 words?  Also, these words will have to be a part of the same dictionary that the Android and iOS wallets use.

**Comment by PeterStaev** [comment]
@gto90 , I'm not 100% sure but the backup function asks you to write down 12 words. Also I have restored using those 12 words on another machine and it restored correctly. But not sure if they use BIP39 or something else (or may be the Derivation Path is different?).

**Comment by gto90** [comment]
ok thanks @PeterStaev , We'll look into this.  Thanks for helping us test!

**Comment by gto90** [comment]
@PeterStaev ,

The new iOS and Android wallets do not support restoring the Chrome GO wallet's seed phrase at this time.  Additionally, Google has announced the deprecation of Chrome apps this year so it is advised that you transfer any balances in your Go wallet to another wallet (not the TestFlight build of the iOS wallet).
