### ISSUE TITLE
Hello, when can I keep money in the iPhone wallet?

### ISSUE THREAD

**Issue by Datsun240** [Racecraft/digibytewallet-ios#137]
**What happened:**
```
Hello, when can I keep money in the iPhone wallet?
```

**Version:** 2.0.0 (1313)

**Operating system:** iOS 11.2.6

**Model:** iPhone 6S

**Memory:** 98% (1.53 GB used out of 1.56 GB)

**Capacity:** 95% (14.2 GB used out of 14.9 GB)

**Battery:** 12%(Unplugged)(Low power mode)

**Locale:** Bulgaria English

**Network:** Carrier HSDPA (3.5G)

**WiFi:** Connected

**Attachments:** 

**URL:** http://buglife.com/apps/breadwallet/reports/99

Reported via Buglife

**Comment by gto90** [comment]
You may keep your DigiByte in the iOS wallet when it becomes available to the general public.
