### ISSUE TITLE
Estimated time to send is too long

### ISSUE THREAD

**Issue by ChillingSilence** [Racecraft/digibytewallet-ios#16]
When sending DGB, the Processing Speed estimates 10-60 minutes
This is 1-6 verifications for Bitcoin (10 min block timing), should be 15-90 seconds to match DigiBytes block timings

![image1](https://user-images.githubusercontent.com/162461/35071682-77d42ae4-fc46-11e7-80b2-6cb552cc0524.jpeg)

Original submitter device information:
App Information:
App Name: DigiWallet - DigiByte Wallet
App Version: 2.0.0 (1200)
Installed App Version: 2.0.0 (1200)

Device Information:
Device: iPhone9,3
iOS Version: 11.2.2
Language: tr-TR (Türkçe (Türkiye))
Carrier: Turk Telekom
Timezone: GMT+3
Architecture: N/A
Connection Status: WiFi
Paired Apple Watch: Apple Watch - Watch OS 4.2 (15S102)

**Comment by gto90** [comment]
Resolved for English locals, but will have to wait until we get the updated localizations to be fully resolved.
