### ISSUE TITLE
Replace current share possibility (email/message) of wallet address to standard iOS share menu

### ISSUE THREAD

**Issue by ploenne** [Racecraft/digibytewallet-ios#165]
Currently sharing of a wallet address is only via Message and Email possible. 
Lets use the standard share menu from iOS share the wallet address all over.

**Comment by SmartArray** [comment]
I don't see whats missing here?
When tapping receive, you can hit share and it opens the standard share menu.

![simulator screen shot - iphone x - 2018-04-24 at 23 09 27](https://user-images.githubusercontent.com/934592/39214384-931f2424-4814-11e8-9a20-fef86e46d1cc.png)
