### ISSUE TITLE
Switching between apps skips the verification of backup

### ISSUE THREAD

**Issue by ChillingSilence** [Racecraft/digibytewallet-ios#17]
During the key words when I got to the confirmation screen requesting 2 words out of the 12 I had to swap apps and when I did that it skipped  the verification and went to this screen. 

![image1](https://user-images.githubusercontent.com/162461/35071736-ab1502ac-fc46-11e7-992a-d8e9176f0999.png)

Original submitter device information:
App Information:
App Name: DigiWallet - DigiByte Wallet
App Version: 2.0.0 (1200)
Installed App Version: 2.0.0 (1200)

Device Information:
Device: iPhone8,2
iOS Version: 11.2.2
Language: en-ZA (English (South Africa))
Carrier: MTN
Timezone: SAST
Architecture: N/A
Connection Status: WiFi
Paired Apple Watch: Apple Watch - Watch OS 4.2 (15S102)

**Comment by gto90** [comment]
This is behaving as designed.  If you ever experience this again, simply go back to the Menu->Security Center and reverify your paper key.
