### ISSUE TITLE
When using a website with DigiID, the DigiWallet starts automatically. When touchID is enabled, the DigiWallet then crashes when given the finger print. Or keeps frozen in the unlock screen (see photo). This does not happen when pin code is used as unlock method.

### ISSUE THREAD

**Issue by Datsun240** [Racecraft/digibytewallet-ios#174]
**What happened:**
```
When using a website with DigiID, the DigiWallet starts automatically. When touchID is enabled, the DigiWallet then crashes when given the finger print. Or keeps frozen in the unlock screen (see photo). This does not happen when pin code is used as unlock method.
```

**Version:** 2.0.0 (1364)

**Operating system:** iOS 11.3

**Model:** iPhone 6S

**Memory:** 98% (1.38 GB used out of 1.4 GB)

**Capacity:** 92% (27.5 GB used out of 29.8 GB)

**Locale:** Netherlands Dutch; Flemish

**Network:** vf nl LTE (4G)

**WiFi:** Connected

**Attachments:** 

![IMG_1794.PNG](http://buglife.s3.amazonaws.com/report_attachments/a645da8aaa69bb975acdbbbcee711b2e40662c40/original/IMG_1794.PNG?1524899117)

**URL:** http://buglife.com/apps/breadwallet/reports/126

Reported via Buglife

**Comment by SmartArray** [comment]
I've successfully fixed this in the new version!
