### ISSUE TITLE
Sync not occurring in the background & additional sync information

### ISSUE THREAD

**Issue by ChillingSilence** [Racecraft/digibytewallet-ios#18]
The wallet is syncing, but the app keeps crashing to home screen.
Also, syncing details are unavailable (blocks information and ect.) like on previous Android wallet.
Should syncing happen only when the app is running? Is it possible to open the wallet and the syncing would happen in the background?

Original submitters device information:
App Information:

App Name: DigiWallet - DigiByte Wallet

App Version: 2.0.0 (1200)

Installed App Version: 2.0.0 (1200)

Device Information:

Device: iPhone9,3

iOS Version: 11.2.2

Language: en-CA (English (Canada))

Carrier: Koodo

Timezone: EST

Architecture: N/A

Connection Status: WiFi

Paired Apple Watch: N/A

**Comment by gto90** [comment]
This crash has been resolved.
