### ISSUE TITLE
Sync process stalling

### ISSUE THREAD

**Issue by ChillingSilence** [Racecraft/digibytewallet-ios#19]
Originally submitted two issues (I believe the second is the primary issue though):

1) during sync proces: went to advanced, dgb nodes.
Result; application crashed.
Bug was not repeated the second time.

2) sync proces seems to be hanging on 13 dec 2017.
When looking in advanced, dgb nodes; the app keeps connecting to new nodes all the time.

Original submitters device information:
App Information:
App Name: DigiWallet - DigiByte Wallet
App Version: 2.0.0 (1200)
Installed App Version: 2.0.0 (1200)

Device Information:
Device: iPhone8,1
iOS Version: 11.2.2
Language: nl-NL (Nederlands (Nederland))
Carrier: vf nl
Timezone: CET
Architecture: N/A
Connection Status: WiFi
Paired Apple Watch: N/A

**Comment by gto90** [comment]
The latest build should improve the quality of the nodes.  However, we are still working on a better long term solution.
