### ISSUE TITLE
Transaction showing unconfirmed even though it has multiple confirms on Blockchain explorer

### ISSUE THREAD

**Issue by ChillingSilence** [Racecraft/digibytewallet-ios#20]
The attached transaction is showing as unconfirmed even though it has many conformations. 
![image1 1](https://user-images.githubusercontent.com/162461/35071958-8ce88dac-fc47-11e7-98ba-c34e7fded876.png)

Original submitters device information: 
App Information:

App Name: DigiWallet - DigiByte Wallet

App Version: 2.0.0 (1213)

Installed App Version: 2.0.0 (1213)

Device Information:

Device: iPhone10,3

iOS Version: 11.2.1

Language: en-US (English (United States))

Carrier: Sprint

Timezone: EST

Architecture: N/A

Connection Status: WiFi

Paired Apple Watch: N/A

**Comment by gto90** [comment]
This issue appears to be resolved in build #1226
