### ISSUE TITLE
Watch application shows incorrect denomination

### ISSUE THREAD

**Issue by ChillingSilence** [Racecraft/digibytewallet-ios#21]
I installed the watch app. The first time I tried to open the app it crashed back to the app screen. Second attempt worked. My balance shows in mmD and I don’t see a way to change that not even in watch options.
![image1 2](https://user-images.githubusercontent.com/162461/35071983-b06826b6-fc47-11e7-98fd-d26e2881482b.png)

Original submitters device information:
App Information:
App Name: DigiWallet - DigiByte Wallet
App Version: 2.0.0 (1214)
Installed App Version: 2.0.0 (1214)

Device Information:
Device: iPhone10,3
iOS Version: 11.2.2
Language: en-US (English (United States))
Carrier: Verizon
Timezone: PST
Architecture: N/A
Connection Status: Cellular data
Paired Apple Watch: Apple Watch - Watch OS 4.2 (15S102)

**Comment by gto90** [comment]
This issue is resolved in build 1226
