### ISSUE TITLE
Wallet freezes after scanning fingerprint (Launched from Widget)

### ISSUE THREAD

**Issue by ChillingSilence** [Racecraft/digibytewallet-ios#22]
When i click the scan qr button from widget, app is opening but freezing after scanning fingerprint.
![image1 3](https://user-images.githubusercontent.com/162461/35072032-db26e144-fc47-11e7-8fc3-ab96d86ded67.png)

![image2](https://user-images.githubusercontent.com/162461/35072045-e17eb724-fc47-11e7-8175-103c442a6def.png)

![image3](https://user-images.githubusercontent.com/162461/35072058-e58b409e-fc47-11e7-9313-dac85b5ff82e.png)

Original submitters device information:
App Information:
App Name: DigiWallet - DigiByte Wallet
App Version: 2.0.0 (1214)
Installed App Version: 2.0.0 (1214)

Device Information:
Device: iPhone9,3
iOS Version: 11.2.2
Language: tr-TR (Türkçe (Türkiye))
Carrier: Turk Telekom
Timezone: GMT+3
Architecture: N/A
Connection Status: WiFi
Paired Apple Watch: Apple Watch - Watch OS 4.2 (15S102)

**Comment by gto90** [comment]
This issue appears to be resolved in build #1226
