### ISSUE TITLE
Initial sync takes ages to complete

### ISSUE THREAD

**Issue by PeterStaev** [Racecraft/digibytewallet-ios#3]
So I've just got invited to the beta and installed the app on an X. Used the option to restore existing wallet (created around 2-3 weeks ago). The sync started but it is very slow (on WiFi). It is running for around 1.5hrs and it is now on 4 Dec 14. Also from time to time it just stalls and I have to force-close the app and reopen it before it continues. Not sure if related to the app itself or server lag/slow.

**Comment by smrycek** [comment]
Same issue here. Mine seems to have stalled within the first 10 minutes on Jan 23, 2014.

**Comment by federicojd** [comment]
Same issue with brand new wallet on wifi too

**Comment by micahqcade** [comment]
Does the app need to be the active application to sync? It seems like it...

**Comment by pbojinov** [comment]
Same issue as well, took me a good 5-6 hours on WiFi to sync to current day. And my internet speed is 100mbps+

**Comment by smrycek** [comment]
An update. I am still attempting to trudge along with this sync several days later. I have managed to get it up to October 2016.  I will get about a week completed before needing to restart the app and get it going again.  Not sure what the issue is here, but the 2-4 estimate is definitely not true on my phone.

**Comment by gto90** [comment]
Please wipe your wallets in the menu, and try restoring your seed phrase using the latest TestFlight build.  Additionally, use manual mode in the advanced settings to use the following node: 37.59.21.58:1202.  Please let me know if that significantly helps you sync.

**Comment by micahqcade** [comment]
My wallet was synced to the block chain and I was able to receive 100 dgb,
but after the update the wallet is resynchronizing again but from 2000, and
doesn't seem to sync when the app is not the active app on iOS.

**Comment by smrycek** [comment]
Hey gto,

I went ahead and switched to manual mode and entered that node. I assumed the port is actually 12024.
It was running, but didn't seem any faster. 

After that, I went ahead and wiped the wallet and then restored it using the 12 word key.  Once I switched it back to manual, I noticed the connection was dropping and then reconnecting continuously in the nodes view.  The dates are still increasing, but the connection to the node is not good. 

Switching back to automatic leads to something similar. It will connect to one and then a short time later disconnect and connect to a new one until it finally settles on, for me, 46.101.122.62:12024 which is still slow.

**Comment by micahqcade** [comment]
I deleted the last version of the wallet (DigiWallet - DigiByte Wallet
2.0.0 (1222) ) and reinstalled it, and now sync is working. The previous
upgrade started the sync @ Dec 2000, once I deleted  and reinstalled the
"fresh" install started the sync @  dec 31 2017, and is quickly moving thru
the dates.  I would love to know if the wallet will sync when it is not the
active app, as it seems as it will not ( the  spinning bar goes away). I
have not restored the wallet ever, but  everytime i have deleted and
reinstalled my balance was correct , and the paper key was the same.
Between versions 1214 and 1218, i think my paper key words had changed, but
from then onward all versions i have installed have had the same paper key.

**Comment by gto90** [comment]
After a fair amount of investigation, this sync performance issue seems to be a result of poorly communicating nodes provided by the seed dns.  We are exploring options to improve this with the core developers.  In the interim, please enable a manual node that you know to be online and responding with the advanced settings.
