### ISSUE TITLE
Request Feature Bitcoin/Shapeshift

### ISSUE THREAD

**Issue by gam777** [Racecraft/digibytewallet-ios#30]
I think a great way to get people using DGB is making it easier for them to get DGB. If we added Bitcoin and possibly Litecoin wallets in the DGB wallet and added the Shapeshift API to allow people to get DGB using their Bitcoin/Litecoin balance easily with their DGB Wallet I think it would help to get easier adoption.
If we're able to get a DGB/USD option instead that would be better. This is just an idea for the future to keep in mind to help people get coins faster and not require them to use too many complicated exchanges.

**Comment by gto90** [comment]
While this is an interest idea, we are focused primarily on getting the core DigiWallet experience up and running.  Once we have a stable and secure wallet, then we can explore additional capabilities like this.
