### ISSUE TITLE
I’m a fake bug that can just be closed immediately.

### ISSUE THREAD

**Issue by Datsun240** [Racecraft/digibytewallet-ios#33]
**What happened:**
```
I’m a fake bug that can just be closed immediately.
```

**Version:** 2.0.0 (1222)

**Operating system:** iOS 11.2

**Model:** Simulator

**Memory:** 100% (14.6 GB used out of 14.6 GB)

**Capacity:** 57% (528 GB used out of 931 GB)

**Locale:** English

**Network:** 

**WiFi:** Connected

**Attachments:** 

![IMG_0001.JPG](http://buglife.s3.amazonaws.com/report_attachments/94b7455c7f791e3dfb076d9b3780d56510d26cc9/original/IMG_0001.JPG?1516419629)

**URL:** http://buglife.com/apps/breadwallet/reports/3

Reported via Buglife

**Comment by gto90** [comment]
BugLife integration is working, closing issue.
