### ISSUE TITLE
2001 sync seems odd 

### ISSUE THREAD

**Issue by Datsun240** [Racecraft/digibytewallet-ios#34]
**What happened:**
```
2001 sync seems odd 
```

**Version:** 2.0.0 (1226)

**Operating system:** iOS 11.2.2

**Model:** iPhone 7

**Memory:** 98% (1.48 GB used out of 1.51 GB)

**Capacity:** 25% (59.5 GB used out of 238 GB)

**Locale:** Germany English

**Network:** Telekom.de LTE (4G)

**WiFi:** Connected

**Attachments:** 

![IMG_6975.PNG](http://buglife.s3.amazonaws.com/report_attachments/8e396032fa5adbe9e23f6e6eb344d41c98404aad/original/IMG_6975.PNG?1516435334)

**URL:** http://buglife.com/apps/breadwallet/reports/4

Reported via Buglife

**Comment by gto90** [comment]
This issue should be resolved in an upcoming TestFlight build
