### ISSUE TITLE
Syncing from January 1. Happened to me three times already. Only fix is to delete, reinstall, and resync the app.

### ISSUE THREAD

**Issue by Datsun240** [Racecraft/digibytewallet-ios#37]
**What happened:**
```
Syncing from January 1. Happened to me three times already. Only fix is to delete, reinstall, and resync the app.
```

**Version:** 2.0.0 (1226)

**Operating system:** iOS 11.0.3

**Model:** iPhone 7 Plus

**Memory:** 87% (2.27 GB used out of 2.6 GB)

**Capacity:** 32% (38.6 GB used out of 119 GB)

**Locale:** Philippines English

**Network:** Carrier HSDPA (3.5G)

**WiFi:** Connected

**Attachments:** 

![Screenshot.png](http://buglife.s3.amazonaws.com/report_attachments/c06f0c85d7fec6323b250f20c2734c5167df82b7/original/Screenshot.png?1516524732)

**URL:** http://buglife.com/apps/breadwallet/reports/6

Reported via Buglife

**Comment by gto90** [comment]
This should be resolved in an upcoming TestFlight build
