### ISSUE TITLE
Just updated to 1228 and checked my paper key; it  does not match the paper key before the update.  I did not delete the app before updating and did not restore a wallet. My balance did not change from the previous version 

### ISSUE THREAD

**Issue by Datsun240** [Racecraft/digibytewallet-ios#38]
**What happened:**
```
Just updated to 1228 and checked my paper key; it  does not match the paper key before the update.  I did not delete the app before updating and did not restore a wallet. My balance did not change from the previous version 
```

**Version:** 2.0.0 (1228)

**Operating system:** iOS 11.2.2

**Model:** iPhone 6S Plus

**Memory:** 98% (1.28 GB used out of 1.31 GB)

**Capacity:** 67% (79.8 GB used out of 119 GB)

**Locale:** United States English

**Network:** Verizon LTE (4G)

**WiFi:** Connected

**Attachments:** 

**URL:** http://buglife.com/apps/breadwallet/reports/7

Reported via Buglife

**Comment by gto90** [comment]
We need more information to debug this issue as we are presently unable to reproduce.
