### ISSUE TITLE
Crashes while I’m waiting to sync 

### ISSUE THREAD

**Issue by Datsun240** [Racecraft/digibytewallet-ios#39]
**What happened:**
```
Crashes while I’m waiting to sync 
```

**Version:** 2.0.0 (1228)

**Operating system:** iOS 11.2.1

**Model:** iPhone 5S

**Memory:** 98% (796 MB used out of 816 MB)

**Capacity:** 91% (13.5 GB used out of 14.9 GB)

**Locale:** Spain Spanish; Castilian

**Network:** Orange España LTE (4G)

**WiFi:** Connected

**Attachments:** 

**URL:** http://buglife.com/apps/breadwallet/reports/8

Reported via Buglife

**Comment by gto90** [comment]
This issue should be resolved in an upcoming TestFlight build.
