### ISSUE TITLE
Setting Limit

### ISSUE THREAD

**Issue by KGB8317** [Racecraft/digibytewallet-ios#4]
When setting a Limit, which would require your Pin for a TX, you cannot enter all digits. Only 5 out of 6 are allowed. After some time the TX times out.
![image](https://user-images.githubusercontent.com/30353416/34900668-58f7d758-f802-11e7-87e7-a1f6b3be33aa.png)
![image](https://user-images.githubusercontent.com/30353416/34900673-636dede4-f802-11e7-800c-795bbb3a4f4a.png)

**Comment by gto90** [comment]
If you have a free moment, can you try enabling a manual node in the advanced settings and attempt to reproduce this issue?
