### ISSUE TITLE
Na een update start de synchronisatie op 31-12-2017. Vervolgens valt toestel in “standby” stand en bij opnieuw inloggen begint de synchronisatie op 01-01-2001


### ISSUE THREAD

**Issue by Datsun240** [Racecraft/digibytewallet-ios#40]
**What happened:**
```
Na een update start de synchronisatie op 31-12-2017. Vervolgens valt toestel in “standby” stand en bij opnieuw inloggen begint de synchronisatie op 01-01-2001

```

**Version:** 2.0.0 (1231)

**Operating system:** iOS 11.2.2

**Model:** iPhone 6

**Memory:** 97% (624 MB used out of 641 MB)

**Capacity:** 84% (12.5 GB used out of 14.9 GB)

**Locale:** Netherlands Dutch; Flemish

**Network:** KPN NL LTE (4G)

**WiFi:** Connected

**Attachments:** 

![IMG_7859.PNG](http://buglife.s3.amazonaws.com/report_attachments/3747c6051d0da70e101d6e2e6519f7ba5192401d/original/IMG_7859.PNG?1516737910)

**URL:** http://buglife.com/apps/breadwallet/reports/9

Reported via Buglife

**Comment by gto90** [comment]
This issue should be resolved in an upcoming TestFlight build
