### ISSUE TITLE
Na synchronisatie van plm. 45min is alles geactualiseerd. Vervolgens sluit ik de wallet en na heropening begint de wallet opnieuw met synchroniseren vanaf 31-12-2017


### ISSUE THREAD

**Issue by Datsun240** [Racecraft/digibytewallet-ios#41]
**What happened:**
```
Na synchronisatie van plm. 45min is alles geactualiseerd. Vervolgens sluit ik de wallet en na heropening begint de wallet opnieuw met synchroniseren vanaf 31-12-2017

```

**Version:** 2.0.0 (1231)

**Operating system:** iOS 11.2.2

**Model:** iPhone 6

**Memory:** 97% (652 MB used out of 670 MB)

**Capacity:** 84% (12.6 GB used out of 14.9 GB)

**Locale:** Netherlands Dutch; Flemish

**Network:** KPN NL LTE (4G)

**WiFi:** Connected

**Attachments:** 

![IMG_7860.PNG](http://buglife.s3.amazonaws.com/report_attachments/83cd43d6f2873c60720d79ad8d1dc40882edb42f/original/IMG_7860.PNG?1516744550)

**URL:** http://buglife.com/apps/breadwallet/reports/10

Reported via Buglife

**Comment by gto90** [comment]
This is a known issue with having difficulty connecting to peers. We are aware of the issue and are working on a solution external from the application.
