### ISSUE TITLE
Tijdens het synchroniseren (45 min) sluit de wallet een aantal malen automatisch af. Na een 6-tal keren afsluiten en weer opnieuw inloggen loopt het synchroniseren wel door.

### ISSUE THREAD

**Issue by Datsun240** [Racecraft/digibytewallet-ios#42]
**What happened:**
```
Tijdens het synchroniseren (45 min) sluit de wallet een aantal malen automatisch af. Na een 6-tal keren afsluiten en weer opnieuw inloggen loopt het synchroniseren wel door.
```

**Version:** 2.0.0 (1231)

**Operating system:** iOS 11.2.2

**Model:** iPhone 6

**Memory:** 98% (663 MB used out of 677 MB)

**Capacity:** 84% (12.6 GB used out of 14.9 GB)

**Locale:** Netherlands Dutch; Flemish

**Network:** KPN NL LTE (4G)

**WiFi:** Connected

**Attachments:** 

**URL:** http://buglife.com/apps/breadwallet/reports/11

Reported via Buglife

**Comment by gto90** [comment]
This crash should be fixed in an upcoming TestFlight build.
