### ISSUE TITLE
When i am clicking scan button from widget, app freeze after scanning fingerprint

### ISSUE THREAD

**Issue by Datsun240** [Racecraft/digibytewallet-ios#43]
**What happened:**
```
When i am clicking scan button from widget, app freeze after scanning fingerprint
```

**Version:** 2.0.0 (1231)

**Operating system:** iOS 11.2.2

**Model:** iPhone 7

**Memory:** 99% (1.42 GB used out of 1.44 GB)

**Capacity:** 79% (23.5 GB used out of 29.8 GB)

**Locale:** Turkey Turkish

**Network:** Turk Telekom LTE (4G)

**WiFi:** Disconnected

**Attachments:** 

![IMG_0797.PNG](http://buglife.s3.amazonaws.com/report_attachments/0c99b50177f5499b8f8f3b602896750f71628c61/original/IMG_0797.PNG?1516753251)

![IMG_0796.PNG](http://buglife.s3.amazonaws.com/report_attachments/f907e3ac66b63aa83cc68a44faaaa277c6c6b42c/original/IMG_0796.PNG?1516753253)

**URL:** http://buglife.com/apps/breadwallet/reports/12

Reported via Buglife

**Comment by gto90** [comment]
This is a known issue with having difficulty connecting to peers. We are aware of the issue and are working on a solution external from the application.
