### ISSUE TITLE
It’s not syncing beyond Dec-28th

### ISSUE THREAD

**Issue by Datsun240** [Racecraft/digibytewallet-ios#45]
**What happened:**
```
It’s not syncing beyond Dec-28th
```

**Version:** 2.0.0 (1233)

**Operating system:** iOS 11.2.2

**Model:** iPhone 7

**Memory:** 97% (1.19 GB used out of 1.22 GB)

**Capacity:** 26% (31.4 GB used out of 119 GB)

**Locale:** Canada English

**Network:** Koodo LTE (4G)

**WiFi:** Connected

**Attachments:** 

**URL:** http://buglife.com/apps/breadwallet/reports/14

Reported via Buglife

**Comment by gto90** [comment]
This is a known issue with having difficulty connecting to peers. We are aware of the issue and are working on a solution external from the application.
