### ISSUE TITLE
Old digibyte mobile wallets had Turkish language option but this is not. How can i comtribute to localize in Turkish? Is it possible?

### ISSUE THREAD

**Issue by Datsun240** [Racecraft/digibytewallet-ios#47]
**What happened:**
```
Old digibyte mobile wallets had Turkish language option but this is not. How can i comtribute to localize in Turkish? Is it possible?
```

**Version:** 2.0.0 (1233)

**Operating system:** iOS 11.2.5

**Model:** iPhone 7

**Memory:** 90% (1.31 GB used out of 1.45 GB)

**Capacity:** 79% (23.4 GB used out of 29.8 GB)

**Locale:** Turkey Turkish

**Network:** Turk Telekom LTE (4G)

**WiFi:** Connected

**Attachments:** 

**URL:** http://buglife.com/apps/breadwallet/reports/16

Reported via Buglife

**Comment by gto90** [comment]
We have some community members contributing to the Turkish locale :)
