### ISSUE TITLE
Na laatste update geen verbetering in het synchronisatie proces. Start op 1-1-2001, daarna geen voortgang in het proces alles staat stil


### ISSUE THREAD

**Issue by Datsun240** [Racecraft/digibytewallet-ios#48]
**What happened:**
```
Na laatste update geen verbetering in het synchronisatie proces. Start op 1-1-2001, daarna geen voortgang in het proces alles staat stil

```

**Version:** 2.0.0 (1233)

**Operating system:** iOS 11.2.2

**Model:** iPhone 6

**Memory:** 98% (659 MB used out of 670 MB)

**Capacity:** 86% (12.8 GB used out of 14.9 GB)

**Locale:** Netherlands Dutch; Flemish

**Network:** KPN NL LTE (4G)

**WiFi:** Connected

**Attachments:** 

![IMG_7879.PNG](http://buglife.s3.amazonaws.com/report_attachments/5a3cd73aed9a3db296c9bd8f4ef626ce8c5de2e1/original/IMG_7879.PNG?1516836072)

**URL:** http://buglife.com/apps/breadwallet/reports/17

Reported via Buglife

**Comment by gto90** [comment]
This is a known issue with having difficulty connecting to peers. We are aware of the issue and are working on a solution external from the application.
