### ISSUE TITLE
Entering IP-adress, comma instead of dot

### ISSUE THREAD

**Issue by KGB8317** [Racecraft/digibytewallet-ios#5]
Can only enter comma's instead of dot for IP-adress In below example, i copy/pasted from a note ![image](https://user-images.githubusercontent.com/30353416/34900725-a755acd6-f802-11e7-94f8-6bed60593307.png)

**Comment by gto90** [comment]
@KGB8317 ,

The latest TestFlight build #1222 should have resolved this for you.  Let me know if you are still seeing the issue.

**Comment by KGB8317** [comment]
Problem solved !
