### ISSUE TITLE
Na update geen verbinding met Primaire Node

### ISSUE THREAD

**Issue by Datsun240** [Racecraft/digibytewallet-ios#50]
**What happened:**
```
Na update geen verbinding met Primaire Node
```

**Version:** 2.0.0 (1233)

**Operating system:** iOS 11.2.2

**Model:** iPhone 6

**Memory:** 98% (673 MB used out of 685 MB)

**Capacity:** 87% (12.9 GB used out of 14.9 GB)

**Locale:** Netherlands Dutch; Flemish

**Network:** KPN NL LTE (4G)

**WiFi:** Connected

**Attachments:** 

**URL:** http://buglife.com/apps/breadwallet/reports/19

Reported via Buglife

**Comment by gto90** [comment]
This is a known issue with having difficulty connecting to peers. We are aware of the issue and are working on a solution external from the application.
