### ISSUE TITLE
Wallet maakt geen contact met Nodes, na herinstallatie wordt er een paar keer gewisseld van node adres ev valt vervolgens weg geen verbinding mogelijk ook niet handmatig

### ISSUE THREAD

**Issue by Datsun240** [Racecraft/digibytewallet-ios#52]
**What happened:**
```
Wallet maakt geen contact met Nodes, na herinstallatie wordt er een paar keer gewisseld van node adres ev valt vervolgens weg geen verbinding mogelijk ook niet handmatig
```

**Version:** 2.0.0 (1233)

**Operating system:** iOS 11.2.2

**Model:** iPhone 6

**Memory:** 98% (660 MB used out of 677 MB)

**Capacity:** 87% (12.9 GB used out of 14.9 GB)

**Locale:** Netherlands Dutch; Flemish

**Network:** KPN NL LTE (4G)

**WiFi:** Connected

**Attachments:** 

**URL:** http://buglife.com/apps/breadwallet/reports/21

Reported via Buglife

**Comment by gto90** [comment]
This is a known issue with having difficulty connecting to peers. We are aware of the issue and are working on a solution external from the application.
