### ISSUE TITLE
Generation 1 Apple Watch:
If you power on watch, and fire up digiwallet app, it consistently crashes twice, and starts up the third time. 

### ISSUE THREAD

**Issue by Datsun240** [Racecraft/digibytewallet-ios#53]
**What happened:**
```
Generation 1 Apple Watch:
If you power on watch, and fire up digiwallet app, it consistently crashes twice, and starts up the third time. 
```

**Version:** 2.0.0 (1233)

**Operating system:** iOS 11.2.1

**Model:** iPhone X

**Memory:** 90% (1.97 GB used out of 2.19 GB)

**Capacity:** 72% (42.6 GB used out of 59.5 GB)

**Locale:** United States English

**Network:** Verizon LTE (4G)

**WiFi:** Connected

**Attachments:** 

**URL:** http://buglife.com/apps/breadwallet/reports/22

Reported via Buglife

**Comment by gto90** [comment]
This should be fixed in an upcoming build.
