### ISSUE TITLE
I was writing down my paper wallet key, on 8th word, app closed and went to home screen

### ISSUE THREAD

**Issue by Datsun240** [Racecraft/digibytewallet-ios#55]
**What happened:**
```
I was writing down my paper wallet key, on 8th word, app closed and went to home screen
```

**Version:** 2.0.0 (1234)

**Operating system:** iOS 11.2.2

**Model:** iPhone 6

**Memory:** 99% (741 MB used out of 750 MB)

**Capacity:** 56% (66.5 GB used out of 119 GB)

**Locale:** United States English

**Network:** AT&T LTE (4G)

**WiFi:** Connected

**Attachments:** 

**URL:** http://buglife.com/apps/breadwallet/reports/24

Reported via Buglife

**Comment by gto90** [comment]
This crash should be fixed in an upcoming build.
