### ISSUE TITLE
Constantly jumps back and forth between connecting and syncing. Over an hour passed at this state. Appears to reset the progress each disconnect. 

### ISSUE THREAD

**Issue by Datsun240** [Racecraft/digibytewallet-ios#58]
**What happened:**
```
Constantly jumps back and forth between connecting and syncing. Over an hour passed at this state. Appears to reset the progress each disconnect. 
```

**Version:** 2.0.0 (1235)

**Operating system:** iOS 11.1.2

**Model:** iPhone X

**Memory:** 95% (2.09 GB used out of 2.19 GB)

**Capacity:** 16% (37.3 GB used out of 238 GB)

**Locale:** United States English

**Network:** Verizon LTE (4G)

**WiFi:** Connected

**Attachments:** 

![Screenshot.png](http://buglife.s3.amazonaws.com/report_attachments/7719f08b513fafe70b59fb8446885eb39767d3ab/original/Screenshot.png?1517011746)

**URL:** http://buglife.com/apps/breadwallet/reports/27

Reported via Buglife

**Comment by gto90** [comment]
This is a known issue with having difficulty connecting to peers. We are aware of the issue and are working on a solution external from the application.
