### ISSUE TITLE
Wallet will not refresh, old receivement still titled 'just now'

### ISSUE THREAD

**Issue by Datsun240** [Racecraft/digibytewallet-ios#61]
**What happened:**
```
Wallet will not refresh, old receivement still titled 'just now'
```

**Version:** 2.0.0 (1235)

**Operating system:** iOS 10.3.3

**Model:** iPhone 6S

**Memory:** 97% (1.29 GB used out of 1.32 GB)

**Capacity:** 78% (46.6 GB used out of 59.6 GB)

**Locale:** Germany German

**Network:** o2-de LTE (4G)

**WiFi:** Connected

**Attachments:** 

![Screenshot.png](http://buglife.s3.amazonaws.com/report_attachments/dc527b57e525cbfe110becb98e88e71659470a57/original/Screenshot.png?1517086072)

**URL:** http://buglife.com/apps/breadwallet/reports/30

Reported via Buglife

**Comment by gto90** [comment]
This is a known issue with having difficulty connecting to peers.  We are aware of the issue and are working on a solution external from the application.
