### ISSUE TITLE
When tried to change pin the screen gets frozen! 

### ISSUE THREAD

**Issue by Datsun240** [Racecraft/digibytewallet-ios#71]
**What happened:**
```
When tried to change pin the screen gets frozen! 
```

**Version:** 2.0.0 (1236)

**Operating system:** iOS 11.1.2

**Model:** iPhone 6S

**Memory:** 94% (1.43 GB used out of 1.52 GB)

**Capacity:** 91% (13.6 GB used out of 14.9 GB)

**Locale:** United States English

**Network:** T-Mobile LTE (4G)

**WiFi:** Connected

**Attachments:** 

**URL:** http://buglife.com/apps/breadwallet/reports/40

Reported via Buglife

**Comment by gto90** [comment]
This issue is resolved in the latest build
