### ISSUE TITLE
Hasn’t been able to sync since the 24th.  Been stuck.  

### ISSUE THREAD

**Issue by Datsun240** [Racecraft/digibytewallet-ios#75]
**What happened:**
```
Hasn’t been able to sync since the 24th.  Been stuck.  
```

**Version:** 2.0.0 (1235)

**Operating system:** iOS 11.2.2

**Model:** iPhone X

**Memory:** 99% (2.25 GB used out of 2.28 GB)

**Capacity:** 11% (27.1 GB used out of 238 GB)

**Locale:** United States English

**Network:** AT&T LTE (4G)

**WiFi:** Connected

**Attachments:** 

![IMG_0313.PNG](http://buglife.s3.amazonaws.com/report_attachments/bcf7945ce5bab45f1940bbc0031344f4216b0da4/original/IMG_0313.PNG?1517264742)

**URL:** http://buglife.com/apps/breadwallet/reports/44

Reported via Buglife

**Comment by PeterStaev** [comment]
I'm also experiencing this problem on iPhone X. It has nothing to do with the specific date. It seems that once initial sync completes after that it stops syncing. When enough days are past to show the progress (not sure how much it is, but seems like 2-3 days behind) it tries to sync and shows the progress but it does not work. Going into Advanced settings shows that it is connected to a node. Force closing the app has no effect. Also tapping on Sync Blockchain option has no effect - it reverts the progress back to 12 Dec 2017, but no progress at all. At that point if you force close the app the progress is returned to the original date that it stalled. The only way is to delete the app and reinstall (installing an update does not solve the problem). 

Note this happens only on iPhone X. I also have an iPhone 6+ and there I do not see this behavior.
